additionalProperties:
  packageVersion: "2.0-alpha"
  packageUrl: "https://github.com/openvinotoolkit/cvat/"
  packageName: "cvat_api_client"
  initRequiredVars: true
  generateSourceCodeOnly: false
globalProperties:
  generateAliasAsModel: true
  apiTests: false
  modelTests: false
enablePostProcessFile: true # requires PYTHON_POST_PROCESS_FILE env var