additionalProperties:
  packageVersion: "2.0-alpha"
  packageUrl: "https://github.com/cvat-ai/cvat"
  packageName: "cvat_sdk"
  initRequiredVars: true
  generateSourceCodeOnly: false
globalProperties:
  generateAliasAsModel: true
  apiTests: false
  modelTests: false
